FROM mysql:8.0

# Dump + script de bootstrap (roda só no 1o boot do volume)
COPY db/init/ /docker-entrypoint-initdb.d/
RUN chmod +x /docker-entrypoint-initdb.d/*.sh \
  && chmod 644 /docker-entrypoint-initdb.d/site-dump.gz
