Write-Host ""
Write-Host "Com Auto-deploy do Railway + GitHub, NAO precisa de secrets de token."
Write-Host ""
Write-Host "No servico wordpress (convivendocomdiabetes) -> Variables, adicione:"
Write-Host "  PORT=80"
Write-Host "  WORDPRESS_DB_HOST=`${{MySQL.MYSQLHOST}}:`${{MySQL.MYSQLPORT}}"
Write-Host "  WORDPRESS_DB_USER=`${{MySQL.MYSQLUSER}}"
Write-Host "  WORDPRESS_DB_PASSWORD=`${{MySQL.MYSQLPASSWORD}}"
Write-Host "  WORDPRESS_DB_NAME=`${{MySQL.MYSQLDATABASE}}"
Write-Host ""
Write-Host "Ative Wait for CI no Source do servico."
Write-Host "Depois: git push na main (ou Redeploy no Railway)."
Write-Host ""
