Write-Host ""
Write-Host "O Account Token (tela account/tokens) NAO funciona bem neste CI."
Write-Host ""
Write-Host "Faca o setup local UMA VEZ:"
Write-Host "  powershell -File scripts/setup-railway-once.ps1"
Write-Host ""
Write-Host "Depois crie Project Token:"
Write-Host "  Projeto Railway -> Settings -> Tokens -> Create"
Write-Host "  Secret no GitHub: RAILWAY_TOKEN"
Write-Host ""
Write-Host "Secrets necessarios:"
Write-Host "  RAILWAY_TOKEN"
Write-Host "  MYSQL_PASSWORD"
Write-Host "  MYSQL_ROOT_PASSWORD"
Write-Host ""
Write-Host "Apague RAILWAY_API_TOKEN do GitHub se existir."
Write-Host ""
